package gob.mefp.reportes.config;

public class ConstantesConfiguracion {
    public enum EnumCodigoAccionBitacora {
        ASIGNACION_ROL("ASIGNACION_ROL"),
        ELIMINACION_ROL("ELIMINACION_ROL"),
        CREACION_OPERACION("CREACION_OPERACION"),
        MODIFICACION_OPERACION("MODIFICACION_OPERACION"),
        ELIMINACION_OPERACION("ELIMINACION_OPERACION"),
        CREACION_TAREA("CREACION_TAREA"),
        MODIFICACION_TAREA("MODIFICACION_TAREA"),
        ELIMINACION_TAREA("ELIMINACION_TAREA"),
        CREACION_PRESUPUESTO("CREACION_PRESUPUESTO"),
        MODIFICACION_PRESUPUESTO("MODIFICACION_PRESUPUESTO"),
        ELIMINACION_PRESUPUESTO("ELIMINACION_PRESUPUESTO"),
        SUBIR_EXCEL_PRESUPUESTO("SUBIR_EXCEL_PRESUPUESTO"),
        COMPLETA_INFORMACION_CONSULTORIA("COMPLETA_INFORMACION_CONSULTORIA"),
        REMISION_TAREAS_MAE("REMISION_TAREAS_MAE"),
        OBSERVAR_TAREAS_ELABORADOR("OBSERVAR_TAREAS_ELABORADOR"),
        SUBIR_EXCEL_PRESUPUESTO_CAMBIO_LEY_FINANCIAL("SUBIR_EXCEL_PRESUPUESTO_CAMBIO_LEY_FINANCIAL"),
        ASIGNACION_ROL_MAE_AUTOMATICA("ASIGNACION_ROL_MAE_AUTOMATICA"),
        CREAR_TRAMITE_MODIFICACION_PRESUP("CREAR_TRAMITE_MODIFICACION_PRESUP"),
        CREAR_TRAMITE_MODIFICACION_PRESUP_FINANCIAL("CREAR_TRAMITE_MODIFICACION_PRESUP_FINANCIAL"),
        REMITIR_TRAMITE_MODIFICACION_PRESUP_GPC("REMITIR_TRAMITE_MODIFICACION_PRESUP_GPC"),
        VISTO_BUENO_TRAMITE_MODIFICACION_PRESUP("VISTO_BUENO_TRAMITE_MODIFICACION_PRESUP"),
        APROBACION_TRAMITE_MODIFICACION_PRESUP("APROBACION_TRAMITE_MODIFICACION_PRESUP"),
        OBSERVAR_TRAMITE_MODIFICACION_PRESUP("OBSERVAR_TRAMITE_MODIFICACION_PRESUP"),
        REVISOR_GPC("REVISOR_GPC"),
        REMITIR_REQUERIMIENTO_POA("REMITIR_REQUERIMIENTO_POA"),
        ;
        public final String codigo;
        EnumCodigoAccionBitacora(String value) {
            this.codigo = value;
        }
    }

}
